[versions]
# libraries
kotlin = "2.3.10"
sollecitom-gradle-plugins = "1.0.0-SNAPSHOT"
sollecitom-swissknife = "1.0.0-SNAPSHOT"
# plugins
palantir-git-plugin = "4.3.0"

[libraries]
sollecitom-gradle-plugins-base = { module = "sollecitom.gradle-plugins:base", version.ref = "sollecitom-gradle-plugins" }
sollecitom-gradle-plugins-kotlin-jvm = { module = "sollecitom.gradle-plugins:kotlin-jvm", version.ref = "sollecitom-gradle-plugins" }
swissknife-kotlin-extensions = { module = "sollecitom.swissknife:kotlin-extensions", version.ref = "sollecitom-swissknife" }
swissknife-test-utils = { module = "sollecitom.swissknife:test-utils", version.ref = "sollecitom-swissknife" }
swissknife-json-utils = { module = "sollecitom.swissknife:json-utils", version.ref = "sollecitom-swissknife" }
swissknife-hashing-utils = { module = "sollecitom.swissknife:hashing-utils", version.ref = "sollecitom-swissknife" }
swissknife-correlation-core-test-utils = { module = "sollecitom.swissknife:correlation-core-test-utils", version.ref = "sollecitom-swissknife" }
swissknife-correlation-core-domain = { module = "sollecitom.swissknife:correlation-core-domain", version.ref = "sollecitom-swissknife" }
swissknife-core-utils = { module = "sollecitom.swissknife:core-utils", version.ref = "sollecitom-swissknife" }
swissknife-core-test-utils = { module = "sollecitom.swissknife:core-test-utils", version.ref = "sollecitom-swissknife" }

[plugins]
com-palantir-git-version = { id = "com.palantir.git-version", version.ref = "palantir-git-plugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
